# Generated by Django 6.0.2 on 2026-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
